export const CHANGE_USERNAME_ACTION = 'CHANGE_USERNAME_ACTION';
export const CHANGE_PASSWORD_ACTION = 'CHANGE_PASSWORD_ACTION'; 
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGIN_SUCCESS_ACTION = 'LOGIN_SUCCESS_ACTION';
export const LOGIN_ERROR_ACTION = 'LOGIN_ERROR_ACTION';
export const PUT_ROLE_ACTION = 'PUT_ROLE_ACTION';