export const GET_MAIN_DRAWER_TAB_VALUE = 'GET_MAIN_DRAWER_TAB_VALUE';
export const CHANGE_MAIN_DRAWER_TAB_VALUE = 'CHANGE_MAIN_DRAWER_TAB_VALUE';

// DAS INNER TAB CONTENT
export const CHANGE_DAS_INNER_TAB_VALUE = 'CHANGE_DAS_INNER_TAB_VALUE';

// DAS ACTION
export const NEW_RIVER_ACTION = 'NEW_RIVER_ACTION';
export const NEW_RIVER_SUCCESS_ACTION = 'NEW_RIVER_SUCCESS_ACTION';

export const UPDATE_RIVER_ACTION = 'UPDATE_RIVER_ACTION';
export const UPDATE_RIVER_SUCCESS_ACTION = 'UPDATE_RIVER_SUCCESS_ACTION';