export const GET_PROJECT_ACTION = 'GET_PROJECT_ACTION';
export const GET_PROJECT_SUCCESS_ACTION = 'GET_PROJECT_SUCCESS_ACTION';
export const GET_PROJECT_FAIL_ACTION = 'GET_PROJECT_FAIL_ACTION';

export const GET_RIVER_ACTION = 'GET_RIVER_ACTION';
export const GET_RIVER_SUCCESS_ACTION = 'GET_RIVER_SUCCESS_ACTION';
export const GET_RIVER_FAIL_ACTION = 'GET_RIVER_FAIL_ACTION';

export const GET_PROJECT_FILES_ACTION = 'GET_PROJECT_FILES_ACTION';
export const GET_PROJECT_FILES_SUCCESS_ACTION = 'GET_PROJECT_FILES_SUCCESS_ACTION';
export const GET_PROJECT_FILES_FAIL_ACTION = 'GET_PROJECT_FILES_FAIL_ACTION';

export const GET_PROJECT_ATTRIBUTE_ACTION = 'GET_PROJECT_ATTRIBUTE_ACTION';
export const GET_PROJECT_ATTRIBUTE_SUCCESS_ACTION = 'GET_PROJECT_ATTRIBUTE_SUCCESS_ACTION';
export const GET_PROJECT_ATTRIBUTE_FAIL_ACTION = 'GET_PROJECT_ATTRIBUTE_FAIL_ACTION';

export const CHANGE_VIEWPORT_ACTION = 'CHANGE_VIEWPORT_ACTION'